use_frameworks!

platform :ios, '9.0'

target 'JITelephoneInputTextField_Example' do
  pod 'JITelephoneInputTextField', :path => '../'

  target 'JITelephoneInputTextField_Tests' do
    inherit! :search_paths

    
  end
end
